### ISSUE TITLE
Dragonprime

### ISSUE THREAD

**Issue by timmyboyox** [lotgd/core#117]
Hello, please can you get 'timmyboyox' approved on DragonPrime. 
Waiting for admin approval and been contacting for days but no one is answering or accepting!

**Comment by stephenKise** [comment]
I will pass this through to Talisman.

**Comment by timmyboyox** [comment]
I appreciate that, very much so!

**Comment by stephenKise** [comment]
Not a problem. If you have any questions feel free to ask. Probably want to close this issue since it is off topic for the repo.

**Comment by timmyboyox** [comment]
Thanks - only done this (knew how to) as Austen recommended it on the repo, if anyone needed to contact him.

**Comment by timmyboyox** [comment]
Hi, thanks Austen - I appreciate it :) can't wait to get on and take a peek at some of the cool modules on there!
