### ISSUE TITLE
Create a skeleton crate for www

### ISSUE THREAD

**Issue by austenmc** [lotgd/core#25]
Take the empty crate-www repo (https://github.com/lotgd/crate-www) and set up a basic crate to serve as a wrapper for the core game.

To make much progress, we need the core to support scenes, but you could at least start with some kind of basic authentication system.

@Vassyli: have a preference for web framework here?

**Comment by Vassyli** [comment]
Not really, no. Maybe laravel or illuminate with laraval-graphql?

**Comment by austenmc** [comment]
@Vassyli created one based on Symfony :)

**Comment by Vassyli** [comment]
https://github.com/lotgd/crate-www/commit/a7f6298646a7e2889360315b4a19510b00226419

Framework used is now symfony with overblog/graphql.
