### ISSUE TITLE
Build a permissions system to control who can post motds, delete users, etc.

### ISSUE THREAD

**Issue by austenmc** [lotgd/core#26]
These permissions should live in a database table, like a mapping between users and permissions. Permissions can be simply strings.

**Comment by Vassyli** [comment]
Shouldn't this be a task for the crate since the create takes care of authentification and authorization?

**Comment by austenmc** [comment]
I don't think so since multiple crates can point at a single DB and I wouldn't want permissions to get out of sync between them.

**Comment by Vassyli** [comment]
I'm not convinced. The core does not know about players, only about characters and what characters do - and characters play the game, they don't admininistrate something.

Registering accounts (which may or may not be linked to one or more characters), authentification of these accounts as well as authorization really should be a task of the crate: He knows who is who and who should be doing what.

Creation of an item could be both an administrative process or a normal gameplay one - so we can't restrict them. But why should we be restricting only selected parts of the core api? It's confusing.

We could provide a default mini-framework that standardizes player accounts and permissions decoupled from the core. This would (if different crates respect this) prevent desynchronisation. But if I want to have a crate that is able to do everything without authorization, I should be able to do this (even if I cannot think about an use-case). After all, the core is only an API that does not provide auth.

**Comment by austenmc** [comment]
Ok, I relent. We can do a real permission system as a module.

But, I think we need well-defined hooks in the right place in the core to support this, like `h/lotgd/core/permission-motd-make` that takes `[ character => '...', result => true ]` and the module can change it to `result => false`.

**Comment by austenmc** [comment]
Actually, I think having a new event type would be what I'd want: `p/lotgd/core/motd-make`

**Comment by Vassyli** [comment]
Ressolved by #78
